publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/htop

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
